cel = 'cells'
pbc = 'periodic_boundary_condition'
elm = 'elements'
sym = 'symbols'
ent = 'entities'
pos = 'positions'
eng_tot = 'total_energies'
eng_mol = 'molecular_energies'
eng_atm = 'atomic_energies'
eng_mol_std = 'molecular_energies_std'
eng_atm_std = 'atomic_energies_std'
eng_res = 'restraints_energies'
frc = 'forces'
mom = 'momenta'
mas = 'masses'
kbt = 'temperatures'
tim = 'times'
dtm = 'delta_times'

chg = 'charge'

ads_frq = 'andersen_frequency'

gam_lng = 'langevin_gamma'

omg_nhc = 'nose_hoover_chain_omega'
pos_nhc = 'nose_hoover_chain_positions'
mom_nhc = 'nose_hoover_chain_momenta'
mas_nhc = 'nose_hoover_chain_masses'
con_nhc = 'nose_hoover_chain_constants'

bme_con = 'blue_moon_const'
bme_lmd = 'blue_moon_lambda'
bme_fix = 'blue_moon_fixman_correction_Z^-0.5'
bme_cor = 'blue_moon_correction_kTG'
bme_pup = 'blue_moon_purpose'

mtd_cen = 'metadynamics_potential_center'
mtd_wdt = 'metadynamics_potential_width'
mtd_hgt = 'metadynamics_potential_height'
mtd_gam = 'metadynamics_bias_factor'
